<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Opd;

class OpdSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $opds = [
            'Badan Kepegawaian Daerah',
            'Badan Kesatuan Bangsa dan Politik Dalam Negeri',
            'Badan Keuangan dan Aset Daerah',
            'Badan Penanggulangan Bencana Daerah',
            'Badan Pendapatan Daerah',
            'Badan Pengembangan Sumber Daya Manusia Daerah',
            'Badan Penghubung Daerah',
            'Badan Perencanaan Pembangunan Daerah',
            'Badan Riset dan Inovasi Daerah',
            'Balai Benih Induk Pertanian (BBI-P)',
            'Balai Bina Jasa Konstruksi dan Pengujian Material',
            'Balai Inseminasi Buatan dan Pengembangan Pakan Ternak',
            'Balai Kemasan, Promosi dan Pemasaran Produk Daerah',
            'Balai KPH Wilayah I',
            'Balai KPH Wilayah II',
            'Balai KPH Wilayah III',
            'Balai KPH Wilayah IV',
            'Balai KPH Wilayah V',
            'Balai KPH Wilayah VI',
            'Balai KPH Wilayah VII',
            'Balai KPH Wilayah VIII',
            'Balai Laboratorium Kesehatan, Pengujian dan Kalibrasi BLU',
            'Balai Laboratorium Lingkungan',
            'Balai Laboratorium Pengujian dan Penerapan Mutu Hasil Perikanan dan Kelautan',
            'Balai Latihan Kerja (Skill Center)',
            'Balai Pelatihan Pertanian',
            'Balai Pembibitan Ternak dan Hijauan Makanan Ternak Serading',
            'Balai Pemeliharaan Jalan Provinsi Pulau Lombok',
            'Balai Pemeliharaan Jalan Provinsi Pulau Sumbawa',
            'Balai Pendidikan dan Pelatihan Koperasi Usaha Kecil dan Menengah',
            'Balai Pengawasan dan Sertifikasi Benih Pertanian (BPSB-P)',
            'Balai Pengawasan Ketenagakerjaan, Keselamatan, dan Kesehatan Kerja Pulau Lombok',
            'Balai Pengawasan Ketenagakerjaan, Keselamatan, dan Kesehatan Kerja Pulau Sumbawa',
            'Balai Pengawasan Mutu dan Keamanan Pangan',
            'Balai Pengelolaan Sumber Daya Air Pulau Lombok',
            'Balai Pengelolaan Sumber Daya Air Pulau Sumbawa',
            'Balai Pengelolaan Sumberdaya Kelautan dan Perikanan Wilayah Bima-Dompu',
            'Balai Pengelolaan Sumberdaya Kelautan dan Perikanan Wilayah Pulau Lombok',
            'Balai Pengelolaan Sumberdaya Kelautan dan Perikanan Wilayah Sumbawa-Sumbawa Barat',
            'Balai Pengembangan Perikanan Budaya',
            'Balai Perlindungan Tanaman Pertanian (BPTP)',
            'Balai Teknologi Informasi dan Data Pendidikan',
            'Biro Hukum dan Hak Asasi Manusia',
            'Biro Kesejahteraan Rakyat',
            'Biro Organisasi',
            'Biro Pemerintahan dan Otonomi Daerah',
            'Biro Pengadaan Barang dan Jasa',
            'Biro Perekonomian dan Administrasi Pembangunan',
            'Biro Umum dan Administrasi Pimpinan',
            'Cabang Dinas Pendidikan, Pemuda dan Olahraga Wilayah I',
            'Cabang Dinas Pendidikan, Pemuda dan Olahraga Wilayah II',
            'Cabang Dinas Pendidikan, Pemuda dan Olahraga Wilayah III',
            'Cabang Dinas Pendidikan, Pemuda dan Olahraga Wilayah IV',
            'Cabang Dinas Pendidikan, Pemuda dan Olahraga Wilayah V',
            'Cabang Dinas Pendidikan, Pemuda dan Olahraga Wilayah VI',
            'Dinas Energi dan Sumber Daya Mineral',
            'Dinas Kebudayaan',
            'Dinas Kelautan dan Perikanan',
            'Dinas Kesehatan',
            'Dinas Komunikasi, Informatika dan Statistik',
            'Dinas Koperasi Usaha Kecil dan Menengah',
            'Dinas Lingkungan Hidup dan Kehutanan',
            'Dinas Pariwisata dan Ekonomi Kreatif',
            'Dinas Pekerjaan Umum, Penataan Ruang, Perumahan dan Kawasan Permukiman',
            'Dinas Pemberdayaan Masyarakat, Pemerintahan Desa, Kependudukan dan Pencatatan Sipil',
            'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu',
            'Dinas Pendidikan, Pemuda dan Olahraga',
            'Dinas Perhubungan',
            'Dinas Perindustrian dan Perdagangan',
            'Dinas Perpustakaan dan Kearsipan',
            'Dinas Pertanian dan Ketahanan Pangan',
            'Dinas Peternakan dan Kesehatan Hewan',
            'Dinas Sosial, Pemberdayaan Perempuan dan Perlindungan Anak',
            'Dinas Tenaga Kerja dan Transmigrasi',
            'Inspektorat',
            'Museum Negeri',
            'Pelabuhan Perikanan Labuhan Lombok',
            'Pelabuhan Perikanan Tanjung Luar',
            'Pelabuhan Perikanan Wilayah Pulau Sumbawa',
            'Perlindungan Perempuan dan Anak',
            'Pusat Pelayanan Sosial Bina Laras Muthmainnah',
            'Pusat Pelayanan Sosial Bina Remaja Karya Wanita dan Penyandang Disabilitas Mirah Adi',
            'Pusat Pelayanan Sosial Lanjut Usia Mandalika',
            'Pusat Pelayanan Sosial Lanjut Usia Meci Angi',
            'Rumah Sakit H. L. Manambai Abdul Kadir BLU',
            'Rumah Sakit Hewan dan Laboratorium Veteriner (BRSHLV)',
            'Rumah Sakit Mandalika BLU',
            'Rumah Sakit Mata BLU',
            'Rumah Sakit Mutiara Sukma BLU',
            'Rumah Sakit Umum Daerah Provinsi NTB BLU',
            'Satuan Polisi Pamong Praja',
            'Sekolah Menengah Kejuruan Pembangunan Pertanian Negeri Bima (SMKPPN Bima)',
            'Sekolah Menengah Kejuruan Pembangunan Pertanian Negeri Mataram (SMKPPN Mataram)',
            'Sekretariat Dewan Perwakilan Rakyat Daerah',
            'SMKN 1 Dompu',
            'SMKN 1 Donggo',
            'SMKN 1 Lingsar',
            'SMKN 1 Praya',
            'SMKN 1 Selong',
            'SMKN 1 Taliwang',
            'SMKN 2 Kota Bima',
            'SMKN 2 Kuripan',
            'SMKN 2 Sumbawa',
            'SMKN 3 Mataram',
            'SMKN 5 Mataram',
            'Taman Budaya',
            'Tempat Pemrosesan Akhir (TPA) Sampah Regional Provinsi NTB',
            'Unit Pelayanan Pajak dan Retribusi Daerah Wilayah I BLU',
            'Unit Pelayanan Pajak dan Retribusi Daerah Wilayah II BLU',
            'Unit Pelayanan Pajak dan Retribusi Daerah Wilayah III BLU',
            'Unit Pelayanan Pajak dan Retribusi Daerah Wilayah IV BLU',
            'Unit Pelayanan Pajak dan Retribusi Daerah Wilayah V BLU',
            'UPTD Destinasi Pariwisata Unggulan Gili Tramena',
        ];

        foreach ($opds as $nama) {
            Opd::firstOrCreate(['nama' => $nama]);
        }
    }
}
